<?php

namespace ContainerQlK8Qd3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SuperAdmin\DashboardController' shared autowired service.
     *
     * @return \App\Controller\SuperAdmin\DashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SuperAdmin/DashboardController.php';

        $container->services['App\\Controller\\SuperAdmin\\DashboardController'] = $instance = new \App\Controller\SuperAdmin\DashboardController();

        $instance->setContainer(($container->privates['.service_locator.g9CqTPp'] ?? $container->load('get_ServiceLocator_G9CqTPpService'))->withContext('App\\Controller\\SuperAdmin\\DashboardController', $container));

        return $instance;
    }
}
