<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQwxK3ei\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQwxK3ei/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerQwxK3ei.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerQwxK3ei\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerQwxK3ei\App_KernelProdDebugContainer([
    'container.build_hash' => 'QwxK3ei',
    'container.build_id' => '6f70d5ac',
    'container.build_time' => 1616429803,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQwxK3ei');
