<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR6Ensfx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR6Ensfx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerR6Ensfx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerR6Ensfx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerR6Ensfx\App_KernelProdContainer([
    'container.build_hash' => 'R6Ensfx',
    'container.build_id' => '9f2814fa',
    'container.build_time' => 1622531256,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR6Ensfx');
