<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDJHKkhJ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDJHKkhJ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerDJHKkhJ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerDJHKkhJ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerDJHKkhJ\App_KernelProdContainer([
    'container.build_hash' => 'DJHKkhJ',
    'container.build_id' => 'cb508f2a',
    'container.build_time' => 1608378397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDJHKkhJ');
