<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZuU9sxk\App_KernelProdDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZuU9sxk/App_KernelProdDebugContainer.php') {
    touch(__DIR__.'/ContainerZuU9sxk.legacy');

    return;
}

if (!\class_exists(App_KernelProdDebugContainer::class, false)) {
    \class_alias(\ContainerZuU9sxk\App_KernelProdDebugContainer::class, App_KernelProdDebugContainer::class, false);
}

return new \ContainerZuU9sxk\App_KernelProdDebugContainer([
    'container.build_hash' => 'ZuU9sxk',
    'container.build_id' => 'a064023e',
    'container.build_time' => 1608377059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZuU9sxk');
