<?php

namespace ContainerREX4rqs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\AkunController::upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SuperAdmin\\AkunController::upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\SuperAdmin\\GerejaController::add' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\SuperAdmin\\GerejaController::reset_password' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Admin\\AkunController:upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\SuperAdmin\\AkunController:upd_keamanan' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\SuperAdmin\\GerejaController:add' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'App\\Controller\\SuperAdmin\\GerejaController:reset_password' => ['privates', '.service_locator.NHPd8E5', 'get_ServiceLocator_NHPd8E5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Admin\\AkunController::upd_keamanan' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\SuperAdmin\\AkunController::upd_keamanan' => '?',
            'App\\Controller\\SuperAdmin\\GerejaController::add' => '?',
            'App\\Controller\\SuperAdmin\\GerejaController::reset_password' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\AkunController:upd_keamanan' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\SuperAdmin\\AkunController:upd_keamanan' => '?',
            'App\\Controller\\SuperAdmin\\GerejaController:add' => '?',
            'App\\Controller\\SuperAdmin\\GerejaController:reset_password' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
