<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIY1F29G\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIY1F29G/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerIY1F29G.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerIY1F29G\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerIY1F29G\App_KernelDevContainer([
    'container.build_hash' => 'IY1F29G',
    'container.build_id' => 'b33ff1c1',
    'container.build_time' => 1614251607,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIY1F29G');
