<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOaugUoh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOaugUoh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOaugUoh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOaugUoh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOaugUoh\App_KernelDevDebugContainer([
    'container.build_hash' => 'OaugUoh',
    'container.build_id' => 'c826073d',
    'container.build_time' => 1614267141,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOaugUoh');
